# Generated by Django 3.2.4 on 2021-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=3)),
                ('empName', models.CharField(max_length=100)),
                ('empMobile', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
